<?php

// Fix clusters that are out of sync because id as been updated 

// For exmaple, if we add missing ION ids with low id numbers, and recluster, and we have 
// new clusters whose cluster_id is one of the newly added values, then we can have both
// new and old clusters in CocuhDB. This code takes a list of names of the newly added
// clusters, checks that they exist in the local MySQL database, if not, it deletes them.

require_once('../lib.php');
require_once ('../config.inc.php');
require_once ('../adodb5/adodb.inc.php');
require_once (dirname(dirname(__FILE__)) . '/couchsimple.php');




//--------------------------------------------------------------------------------------------------
$db = NewADOConnection('mysql');
$db->Connect("localhost", 
	$config['db_user'] , $config['db_passwd'] , $config['db_name']);

// Ensure fields are (only) indexed by column name
$ADODB_FETCH_MODE = ADODB_FETCH_ASSOC;



$names = array('Rhadinoceraea lucida');

$names = array(
'Malenia',
'Rhadinoceraea lucida',
'Macropsis baicalica',
'Colasposoma purpureicolor',
'Lissonota formosa',
'Cavariella konoi',
'Acelyphus repletus',
'Sabethes albiprivus',
'Taeniorhynchus (Coquillettidia) tenuipalpis',
'Dixella clavulus',
'Phoniomyia quasilongirostris',
'Wyeomyia antillarum',
'Wyeomyia colsord',
'Saemundssonia p. frater',
'Afrephialtes',
'Holcopimpla',
'Beckerina nigricornis',
'Bruchus cubiculus',
'Bruchus speciosus',
'Trechus pumilus',
'Monophadnus minutus',
'Lamprophaes',
'Saemundssonia p. nitzschi',
'Paramyiomma',
'Diaborus nebraskensis',
'Haemagogus splendens',
'Bruchus ramicornis',
'Culex inornatus',
'Trophithauma splendidum',
'Monophadnus aeratus',
'Bruchus bivulneratus',
'Tenthredo inhabilis',
'Macrosteles zachvatkini',
'Athysanus sachalinensis',
'Ctenochira helveticator',
'Culex (C.) quinquefasciatus',
'Sabethes albiprivatus',
'Chalicidoma (P.) r. maurusia',
'Formica (F.)',
'Paracharactus nigrisomus',
'Osmia perezi',
'Hoplia lahulensis',
'Aedes nubilis',
'Lyda flagellicornis',
'Chaetomastrus',
'Paratiphia nevadensis',
'Craterocercus circulus',
'Ephemerella orestes',
'Paracharactus obtentus',
'Takagia',
'Agromyza reverberata',
'Bruchus chiricahuae',
'Hemiglobus',
'Culex secutor',
'Toxorhynchites violaceus',
'Wyeomyia argenteorostris',
'Wyeomyia rorotai',
'Puliciphora spinicollis',
'Bruchus serratifemur',
'Embolorrhinus l. intermedia',
'Enicocephalus fossilis',
'Erythraspides',
'Bruchus inquisitus',
'Psorophora blanchardi',
'Micromonodon',
'Altica flavipes',
'Wyeomyia bodkini',
'Thysonotis subsuleima',
'Culex aestuans',
'Micropus variegatus',
'Bruchus collusus',
'Phytobia pollinosa',
'Periclista leucostoma',
'Aedes spencerii',
'Selandria nubilipennis',
'Melandoselandria zabriskiei',
'Culex inflictus',
'Toxorhynchites lunatum',
'Nabis flavomarginatus',
'Brachythops flavens',
'Stilpnus anthomyidiperda',
'Meotica clavata',
'Blepharidites',
'Coleophora gazella',
'Coleophora magnatella',
'Atomacera',
'Agallia nigra',
'Acelyphus lyneborgi',
'Wyeomyia negrensis',
'Euodynerus variegatus',
'Medophron',
'Bruchus knulli',
'Bruchus rufovittatus',
'Megaselia (A.) monochaeta',
'Pseudoplastophora',
'Megachile asiatica',
'Psorophora terminalis',
'Thamnotettix pallidipennis',
'Cryptocephalus multicoloratus',
'Ischnodemus longus',
'Bathysmatophorus linnavuorii',
'Myrmecocystus cinnamomea',
'Manobia africana',
'Simulium wolcotti',
'Baryntica',
'Meibomeus Musculus',
'Bruchus biustulus',
'Bruchus schaefferi',
'Megaselia (M.) malacophaga',
'Culex kelloggii',
'Eupteryx takasagonis',
'Aedes hirsuteron',
'Phyzelus',
'Osmia usbekistana',
'Toxorhynchites nivipes',
'Thaumastomerus',
'Rhabdophaga sauciperda',
'Rhysotrachelus jokoensis',
'Siphocoryne angelicae',
'Messor',
'Ilolaus (Iolaphilus) aelianus',
'Bruchus discolor',
'Chalicidoma muraria var. tingitana',
'Dizygomyza luteiceps',
'Bruchus prosopoides',
'Haltica',
'Heteromurus dubius',
'Acelyphus',
'Opifex fuscus',
'Culex annuliventris',
'Mansonia pseudotitillans',
'Psorophora molesta',
'Meotica apicalis',
'Megaselia (M.) aterrima',
'Bruchus nigrinus',
'Bruchus quadridentatus',
'Blennocampa angulata',
'Monolepta luperoides',
'Rhyparida basileptoides',
'Rhorus chrysopyga',
'Culex atratus',
'Culex pungens',
'Phytobia longipennis',
'Hylodromus dilaticornis',
'Diploneyra igloneura borgmeieri',
'Tenthredo barda',
'Phoniomyia fuscipes',
'Liriomyza triglochinae',
'Macrosteles romanovi',
'Myrmecocystus melliger',
'Bradysia nec',
'Megabombus (Rhodobombus) pomorum',
'Diaborus citrifrons',
'Melandoselandria',
'Kytorhinus pygidialis',
'Osmia papaveris var. convolvuli',
'Bruchus mixtus',
'Monophadnoides conductus',
'Bozakites',
'Tenthredo afra',
'Toxorhynchites purpureus',
'Periclistini',
'Rhabdophaga albipennis',
'Trogaspidia castellana',
'Tenosis',
'Culex cubensis',
'Bentyra',
'Stiboscopus',
'Bruchus vacillator',
'Mutilla castellana',
'Dizygomyza karli',
'Lithraeus electus',
'Astatus tenuicornis',
'Craterocercus cervinus',
'Psorophora albipes',
'Paratiphia fuscinerva',
'Rarivia',
'Parascarabaeus',
'Culex humilis',
'Homaspis nigripes',
'Phytagromyza orbitalis',
'Culex innominatus',
'Melanagromyza heterothecae',
'Tenthredo limhergorum',
'Stilpnus americanus',
'Phytomyza harlemensis',
'Culex paganus',
'Culex scholasticus',
'Wanderbiltiana minor',
'Hemiteles bifasciatus',
'Phoniomyia trinidadensis',
'Pareophora guana',
'Phytobia inconspicua',
'Paradixa',
'Culex argenteoumbrosus',
'Culex infoliatus',
'Reduviolus vanduzeei',
'Flavopimpla',
'Monomorium',
'Aritranis',
'Triphleba h. tnohrae',
'Ecituncula setosa',
'Bruchus auetus',
'Embolorrhinus (E.) tuberculatus',
'Phytagromyza plagiata',
'Wyeomyia luteoventralis',
'Blepharida bimbiensis',
'Eutomostethus gagathinus meridionalis',
'Culex innovator',
'Gnesia',
'Pheideole',
'Cnemidanomia ussuriensis',
'Altica',
'Trechus sinuatus',
'Psorophora cilipes',
'Delaulax',
'Pammene snellenana',
'Tetramorium',
'Borophaga fuscipalpis',
'Culex nigrocorpus',
'Wyeomyia albosquamata',
'Culex fatigans',
'Toxorhynchites frontosum',
'Eudiaborus promediatus promediatus',
'Bathythrix striatus',
'Ivondrites?',
'Bruchus protractus',
'Toxorhynchites horei',
'Dizygomyza (Poemyza) pygmella',
'Psorophora fiebrigi',
'Bruchus elegans',
'Ctenophthalmus capriciosus bychowkyi',
'Aedes vittatus',
'Lepyroniella',
'Plea borellii',
'Napomyza lonicerella',
'Culex janitor',
'Selandria scelesta',
'Psorophora apicalis',
'Toxorhynchites aldrichanus',
'Bombus (Agrobombus) mucidus m. macedonicus',
'Bothriomyrmex',
'Mesostenus temporalis',
'Bruchus pugiunculus',
'Bruchus pygidialis',
'Homotyphus',
'Coenobius longicornis',
'Paracharactus rudis',
'Puliciphora amoena',
'Romicpus flavitarsus',
'Cnemidanomia',
'Myiomma',
'Enallagma risi',
'Heikertingerella',
'Aedes annuliferus',
'Psorophora pallescens',
'Osmiini (Megachilidae)',
'Crematogaster',
'Takastenus',
'Bruchus abbreviatus',
'Oxycara cribata',
'Cryptocephalus zavattarii',
'Basilewskyana brittoni',
'Bruchus pauperculus',
'Culex microsquamosus',
'Ischnodemus atramedius',
'Ischnodemus rufipes',
'Monophadnus (Pseudoblennocampa)',
'Phytobia thompsoni',
'Wyeomyia grayii',
'Disphaerocephalus',
'Acrotrichis satsumanis',
'Saemundssonia p. mollis',
'Phyzelus fasciatus',
'Culex palus',
'Culex originator',
'Toxorhynchites theobaldi',
'Osmia (Aceratosmia) fedtschenkoi',
'Megachile lefebvrei',
'Hemipterochilus fairmairi',
'Bruchus brunneostictus',
'Toxorhynchites moengoensis',
'Brasilaphthona amazona',
'Sabethes argyronotum',
'Megabombus (Rhodobombus) armeniacus',
'Cavariella salicis',
'Paratiphia insueta',
'Batrachomorphus orientalis',
'Agromyza clara',
'Tryphon apritinus',
'Glenidion',
'Diaborus glutinatus var. inversus',
'Debilos',
'Euromonzia',
'Emmenastus compactus',
'Alfkenia?',
'Ctenopelma primosa',
'Chalicodoma rufitarsis',
'Agromyza magnicornis',
'Paratiphia sumichrasti',
'Erythraspides tuckeri',
'Limnophila (Phylidorea) umbrarum',
'Dosa',
'Eclytus fontinalis',
'Campoplex',
'Paratiphia varipunctata',
'Disphaerocephalus swinhoei',
'Glyphicnemis',
'Wyeomyia occulta',
'Selandria serva fuscitarsis',
'Blennocampa aperta',
'Coenobius bicolor',
'Agromyza impatientis',
'Geoblissus hirtulus',
'Hemichroa phytophagica',
'Monolepta excavata',
'Didymocephalus a. occipitalis',
'Aedes luciensis',
'Chalicidoma (Parachalicodoma) rufitarsis',
'Bruchus fumatus',
'Hypolampsis ephippium',
'Monophadnus bipunctatus',
'Embolorrhinus (Embolorrhinus) leleupi',
'Tolonus',
'Psorophora goeldii',
'Amasissarta bleyli',
'Basilepta bieoloratum',
'Clitena fulva',
'Cerodontha (Poemyza)',
'Phytagromyza populicola',
'Agromyza phytomyzina',
'Syphraea',
'Wyeomyia flui',
'Dolerus geniculates',
'Eudiaborus promediatus cressoni',
'Oxycara compacta',
'Megaselia (M.) ucutangula',
'Melaloncha ronnai',
'Bruchus discoideus',
'Hoplia grisea',
'Wyeomyia fallax',
'Ephemerella jacobi',
'Colaspoides tarsalts',
'Monophadnoides cordatus',
'Cnemidanomia lugubris',
'Alagoasca',
'Embolorrhinus leleupi curtipennis',
'Canodia? camera',
'Osmia (Ceratosmia balucha)',
'Didymocephalus curculio villiersi',
'Paratiphia pachucae',
'Cymophyes africana',
'Hephathus pygmaeus',
'Idiocerus suturalis',
'Sphaeroderma apicatum',
'Absyrtus vernalis',
'Psorophora sdntillans',
'Meotica exiliformis',
'Meotica lohsei',
'Chalicidoma (Allochalicodoma) lefebvrei',
'Strongylognathus',
'Tapinoma',
'Ceratophygadeuon',
'Lemurella',
'Bruchus innotatus',
'Haltica regalis',
'Liriomyza pacifica',
'Koshunia',
'Agromyza lygophepa',
'Diodontops',
'Periclista chionanthi',
'Acerastes',
'Syzeuctus decorata',
'Blennocampa abnorma',
'Blastopsocidus',
'Sciara lafooni',
'Aedes canadensis',
'Psorophora cingulata',
'Sabethes purpureus',
'Paratiphia intermedia',
'Phora concinna',
'Wyeomyia albocaerulea',
'Geotrupes (T.) chersinus',
'Nothodixa',
'Chlorita transvera',
'Culex indecorabilis',
'Spaniocelyphus',
'Dialges frontalis',
'Coleophora candidella',
'Cryptocephalus subsuturalis',
'Phytagromyza nitida',
'Bradysia tritici',
'Cavariella angelicae',
'Didymocephalus anthocoroides var. vittipes',
'Blennocampa adusta',
'Culex',
'Coquillettidia arribalzagae',
'Culex saramaccensis',
'Psorophora antiguae',
'Psorophora tovari',
'Aedes aurites',
'Psorophora lutzii',
'Cryptocephalus nigroscutus',
'Bruchus macrophthalmus',
'Phytomyza delphiniae',
'Toxorhynchites guianensis',
'Sciara johannseni',
'Eudiaborus boreoalpinus',
'Parabolocratus erythrapygus',
'Thamnotettix nigrovittatus',
'Dizygomyza (Cephalomyza)',
'Didymocephalus anthocoroides occipitalis',
'Meotica Strandi',
'Beckerina lucifrons',
'Timomenus zeae',
'Dolerus africanus',
'Urocerus a. bensoni',
'Solenopsis',
'Diploneyra aurihalterata',
'Hyperallus virginiensis',
'Psorophora pygmaea',
'Allantus diversipes',
'Culex bilineatus',
'Formica (Coptoformica)',
'Paratrechima',
'Homaspis albipes',
'Iphitrea',
'Camponotus (C.) (sensu stricto)',
'Phytomyza dura',
'Tenthredo sachalinensis',
'Didymocephalus anthocoroides',
'Aedes impiger',
'Culex multispinosus',
'Bruchus alboguttis',
'Thysonotis dispar latifascia',
'Culex nicceriensis',
'Culex pleuristriatus',
'Pammene agnotana',
'Temnothorax',
'Charitopes',
'Mastrus',
'Monophadnoides',
'Bruchus pythonicus',
'Bruchus depressus',
'Phoniomyia longirostris',
'Cteniscus',
'Acanthoscelides compressicornis',
'Cavariella hendersoni',
'Hypargyricus infuscatus',
'Paramesus major',
'Priopoda sticta aegyptiator',
'Henicocephalus tuberculicollis',
'Culex quasisecutor',
'Stenamma',
'Lymeon',
'Acontistoptera ecitonis',
'Megaselia (M.) lutelcornis',
'Idiostoma?',
'Colposcelis',
'Sciara (Lycoriella) latistylata',
'Osmia hierosolomita',
'Bruchus lobatus',
'Schizopleuron',
'Halidamia',
'Craterocercus fraternalis',
'Sabethes nitidus',
'Acanthoscelides pauperculus',
'Bruchus biguttatus',
'Formica (Serviformicd)',
'Aphadnus rufipes',
'Phoniomyia splendida',
'Cryptocephalus bicoloricornis',
'Stiboscopus grenadensis',
'Bruchus subserripes',
'Cerodontha (Dizygomyza) morosa',
'Cavariella',
'Limatus pseudomethysticus',
'Wyeomyia ulocoma',
'Hodostates',
'Sennius cruentatus',
'Hyposoter',
'Tenthredo sahariensis',
'Blennocampa antennata',
'Phytobia subinfumata',
'Dimorphopterus',
'Erythroneura ussurica?',
'Sterictiphora',
'Aedes sollicitans',
'Cryptocephalus biluteomaculatus',
'Luperus anthracinus',
'Mesochorus phyllotretae',
'Orthizema',
'Dialges intensicolor',
'Bruchus perplexus',
'Blennocampa acuminata',
'Cavariella hillerislambersi',
'Plagiolepis',
'Erythroneura salisic?',
'Athysanus suturalis',
'Elymana longispina',
'Bruchus californicus',
'Cornaria',
'Soratsia',
'Bathyplectes',
'Phytagromyza luteoscutellata',
'Lasius',
'Trachysphyrus',
'Mesostenus americanus',
'Isotomiella bidentata',
'Myrmica',
'Bruchus discopterus',
'Bruchus erythrocents',
'Archipsocopsis',
'Claremontia',
'Cardiocondyla',
'Tenthredo adequata'
);



foreach ($names as $name)
{
	$url = 'http://direct.bionames.org:5984/bionames/_design/taxonName/_view/nameString?key=' . urlencode('"' . $name . '"');

	$json = get($url);
	
	echo $json;
	
	if ($json != '')
	{
		$ids = array();
		
		$obj = json_decode($json);
		
		foreach ($obj->rows as $row)
		{
		
			$cluster_id = str_replace('cluster/', '', $row->id);
			
			echo $cluster_id . "\n";
			
			$sql = 'SELECT * FROM `names` WHERE cluster_id="' . $cluster_id . '" LIMIT 1';
			
			$result = $db->Execute($sql);
			if ($result == false) die("failed [" . __FILE__ . ":" . __LINE__ . "]: " . $sql);
	
			if ($result->NumRows() == 0)
			{
				$ids[] = $cluster_id;
			}
			
		}
		
		
		echo "Delete\n";
		print_r($ids);

		foreach ($ids as $id)
		{
			// delete 
			$cluster_id = 'cluster/' . $id;
			$couch->add_update_or_delete_document(null, $cluster_id, 'delete');
		}		
		
		
	}
		
		
	
}



?>

